// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {ffmpeg} from '../models';
import {cli} from '../models';
import {project} from '../models';
import {metrics} from '../models';

export function CancelRun():Promise<void>;

export function DefaultRawFormat(arg1:string):Promise<ffmpeg.RawFormat>;

export function DetectFFmpeg():Promise<ffmpeg.ProbeInfo>;

export function GetInitialOptions():Promise<cli.Options>;

export function IsRawVideo(arg1:string):Promise<boolean>;

export function LoadProject(arg1:string):Promise<project.Project>;

export function MakeThumbnail(arg1:string):Promise<string>;

export function MakeThumbnailRaw(arg1:string,arg2:ffmpeg.RawFormat):Promise<string>;

export function MediaInfo(arg1:string):Promise<ffmpeg.MediaInfo>;

export function MediaInfoRaw(arg1:string,arg2:ffmpeg.RawFormat):Promise<ffmpeg.MediaInfo>;

export function SaveFileDialog(arg1:string,arg2:string):Promise<string>;

export function SaveProject(arg1:string,arg2:project.Project):Promise<void>;

export function SelectDirectory(arg1:string):Promise<string>;

export function SelectFiles(arg1:boolean,arg2:string):Promise<Array<string>>;

export function StartRun(arg1:metrics.RunRequest):Promise<void>;
